-- Schema snapshot (repo-hygiene for the Jul 2026 audit). These objects ALREADY EXIST
-- in the live Supabase DB; captured here so a fresh provision reproduces them and the
-- repo documents ground truth. IF NOT EXISTS / OR REPLACE make this a safe/idempotent
-- no-op on the live DB.
--
-- The pgcrypto app-secret + site-secret RPCs (set/get_app_secret, set/get_site_secret_srv)
-- are canonically defined WITH their REVOKE-from-PUBLIC hardening in supabase/n8n-secret.sql
-- and supabase/migration-secrets.sql — so they are NOT duplicated here. This file owns the
-- GSC + Airtable credential RPCs + their secret tables (which had no committed home).
-- prompts.temperature also already exists live.

create table if not exists public.airtable_config (
  id uuid default gen_random_uuid() not null,
  site_id uuid,
  base_id text,
  table_gaps text,
  table_content text,
  table_geo text,
  connected boolean default false,
  last_sync timestamptz,
  created_at timestamptz default now()
);

create table if not exists public.airtable_sync_log (
  id uuid default gen_random_uuid() not null,
  site_id uuid,
  kind text,
  records_pushed integer default 0,
  status text,
  detail text,
  created_at timestamptz default now()
);

create table if not exists public.chat_conversations (
  id uuid default gen_random_uuid() not null,
  site_id uuid,
  title text default 'New chat'::text,
  messages jsonb default '[]'::jsonb,
  api_history jsonb default '[]'::jsonb,
  message_count integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.geo_runs (
  id uuid default gen_random_uuid() not null,
  site_id uuid,
  engine text default 'claude'::text,
  share_of_voice numeric,
  prompts_total integer,
  prompts_cited integer,
  results jsonb,
  competitors jsonb,
  created_at timestamptz default now()
);

create table if not exists public.gsc_daily (
  id bigint generated by default as identity primary key,
  site_id uuid,
  date date not null,
  query text,
  page text,
  dim text default 'query'::text,
  clicks integer default 0,
  impressions integer default 0,
  ctr numeric default 0,
  position numeric default 0,
  created_at timestamptz default now()
);

create table if not exists public.semrush_snapshots (
  id uuid default gen_random_uuid() not null,
  site_id uuid,
  domain text,
  kind text,
  payload jsonb,
  created_at timestamptz default now()
);

create table if not exists public.user_settings (
  owner uuid not null,
  kill_switch boolean default false not null,
  updated_at timestamptz default now() not null
);

-- Encrypted-credential stores read/written by the GSC + Airtable RPCs below (bytea =
-- pgp_sym_encrypt output). site_id is the PK (one credential per site).
create table if not exists public.gsc_secrets (
  site_id uuid primary key,
  sa_enc bytea,
  property text,
  updated_at timestamptz default now()
);

create table if not exists public.airtable_secrets (
  site_id uuid primary key,
  pat_enc bytea,
  updated_at timestamptz default now()
);


-- ── GSC + Airtable credential RPCs (pgcrypto SECURITY DEFINER) ──────────────────────
-- Referenced by backend-api/supabase.js but previously in no committed migration.

create or replace function public.get_airtable_pat(p_site uuid, p_key text)
 RETURNS text LANGUAGE plpgsql SECURITY DEFINER
AS $function$ declare v text; begin select pgp_sym_decrypt(pat_enc, p_key) into v from airtable_secrets where site_id=p_site; return v; end $function$
;

create or replace function public.set_airtable_pat(p_site uuid, p_pat text, p_key text)
 RETURNS void LANGUAGE plpgsql SECURITY DEFINER
AS $function$ begin insert into airtable_secrets(site_id, pat_enc) values (p_site, pgp_sym_encrypt(p_pat, p_key)) on conflict (site_id) do update set pat_enc=excluded.pat_enc, updated_at=now(); end $function$
;

create or replace function public.get_gsc_sa(p_site uuid, p_key text)
 RETURNS text LANGUAGE plpgsql SECURITY DEFINER
AS $function$ declare v text; begin select pgp_sym_decrypt(sa_enc, p_key) into v from gsc_secrets where site_id=p_site; return v; end $function$
;

create or replace function public.set_gsc_sa(p_site uuid, p_sa text, p_key text)
 RETURNS void LANGUAGE plpgsql SECURITY DEFINER
AS $function$ begin insert into gsc_secrets(site_id, sa_enc) values (p_site, pgp_sym_encrypt(p_sa, p_key)) on conflict (site_id) do update set sa_enc=excluded.sa_enc, updated_at=now(); end $function$
;

-- Harden: a SECURITY DEFINER pgcrypto function is world-executable by default (EXECUTE
-- granted to PUBLIC). Revoke that and grant only the service role (the backend) — else
-- any Postgres role, incl. anon, could decrypt stored credentials.
revoke all on function public.get_airtable_pat(uuid, text) from public;
revoke all on function public.set_airtable_pat(uuid, text, text) from public;
revoke all on function public.get_gsc_sa(uuid, text) from public;
revoke all on function public.set_gsc_sa(uuid, text, text) from public;
grant execute on function public.get_airtable_pat(uuid, text) to service_role;
grant execute on function public.set_airtable_pat(uuid, text, text) to service_role;
grant execute on function public.get_gsc_sa(uuid, text) to service_role;
grant execute on function public.set_gsc_sa(uuid, text, text) to service_role;
